In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 51, (5, 4))
print(arr)

[[50 24 15 41]
 [ 8 15 31  4]
 [15 21  8  3]
 [50  5 30 23]
 [32 50 35 21]]


In [3]:
anti_diagonal = [arr[i][3 - i] for i in range(min(arr.shape))]
print(anti_diagonal)

[np.int64(41), np.int64(31), np.int64(21), np.int64(50)]


In [4]:
row_max = np.max(arr, axis=1)
print(row_max)

[50 31 21 50 50]


In [6]:
mean_val = np.mean(arr)
new_arr = arr[arr <= mean_val]
print(new_arr)

[24 15  8 15  4 15 21  8  3  5 23 21]


In [7]:
def numpy_boundary_traversal(matrix):
    top = matrix[0]
    right = matrix[1:-1, -1]
    bottom = matrix[-1][::-1]
    left = matrix[-2:0:-1, 0]
    return list(top) + list(right) + list(bottom) + list(left)

In [8]:
print(numpy_boundary_traversal(arr))

[np.int64(50), np.int64(24), np.int64(15), np.int64(41), np.int64(4), np.int64(3), np.int64(23), np.int64(21), np.int64(35), np.int64(50), np.int64(32), np.int64(50), np.int64(15), np.int64(8)]
